name: test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install modules
        run: npm install

      - name: Validate dist folder
        run: npm run build --silent && git diff --quiet dist || { echo "dist files should be generated" ; exit 62; }

      - name: Run tests
        run: npm test

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        if: success()
        with:
         file: ./coverage/clover.xml

      - name: Run tests for all js files
        run: npx jest
